version: '3'
services:
  mysql:
    image: mysql:8.0
    container_name: custom-container-name
    environment:
      MYSQL_ROOT_PASSWORD: root-user-password
      MYSQL_DATABASE: db-name
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  
volumes:
  mysql_data:
